// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/waza/internal/execution (interfaces: copilotSession,copilotClient)
//
// Generated by this command:
//
//	mockgen -package execution -destination copilot_client_wrapper_mocks_test.go . copilotSession,copilotClient
//

// Package execution is a generated GoMock package.
package execution

import (
	context "context"
	reflect "reflect"

	copilot "github.com/github/copilot-sdk/go"
	gomock "go.uber.org/mock/gomock"
)

// MockcopilotSession is a mock of copilotSession interface.
type MockcopilotSession struct {
	ctrl     *gomock.Controller
	recorder *MockcopilotSessionMockRecorder
	isgomock struct{}
}

// MockcopilotSessionMockRecorder is the mock recorder for MockcopilotSession.
type MockcopilotSessionMockRecorder struct {
	mock *MockcopilotSession
}

// NewMockcopilotSession creates a new mock instance.
func NewMockcopilotSession(ctrl *gomock.Controller) *MockcopilotSession {
	mock := &MockcopilotSession{ctrl: ctrl}
	mock.recorder = &MockcopilotSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcopilotSession) EXPECT() *MockcopilotSessionMockRecorder {
	return m.recorder
}

// On mocks base method.
func (m *MockcopilotSession) On(handler copilot.SessionEventHandler) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "On", handler)
	ret0, _ := ret[0].(func())
	return ret0
}

// On indicates an expected call of On.
func (mr *MockcopilotSessionMockRecorder) On(handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "On", reflect.TypeOf((*MockcopilotSession)(nil).On), handler)
}

// SendAndWait mocks base method.
func (m *MockcopilotSession) SendAndWait(ctx context.Context, options copilot.MessageOptions) (*copilot.SessionEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndWait", ctx, options)
	ret0, _ := ret[0].(*copilot.SessionEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAndWait indicates an expected call of SendAndWait.
func (mr *MockcopilotSessionMockRecorder) SendAndWait(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndWait", reflect.TypeOf((*MockcopilotSession)(nil).SendAndWait), ctx, options)
}

// SessionID mocks base method.
func (m *MockcopilotSession) SessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockcopilotSessionMockRecorder) SessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockcopilotSession)(nil).SessionID))
}

// MockcopilotClient is a mock of copilotClient interface.
type MockcopilotClient struct {
	ctrl     *gomock.Controller
	recorder *MockcopilotClientMockRecorder
	isgomock struct{}
}

// MockcopilotClientMockRecorder is the mock recorder for MockcopilotClient.
type MockcopilotClientMockRecorder struct {
	mock *MockcopilotClient
}

// NewMockcopilotClient creates a new mock instance.
func NewMockcopilotClient(ctrl *gomock.Controller) *MockcopilotClient {
	mock := &MockcopilotClient{ctrl: ctrl}
	mock.recorder = &MockcopilotClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcopilotClient) EXPECT() *MockcopilotClientMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockcopilotClient) CreateSession(ctx context.Context, config *copilot.SessionConfig) (copilotSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, config)
	ret0, _ := ret[0].(copilotSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockcopilotClientMockRecorder) CreateSession(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockcopilotClient)(nil).CreateSession), ctx, config)
}

// ResumeSessionWithOptions mocks base method.
func (m *MockcopilotClient) ResumeSessionWithOptions(ctx context.Context, sessionID string, config *copilot.ResumeSessionConfig) (copilotSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSessionWithOptions", ctx, sessionID, config)
	ret0, _ := ret[0].(copilotSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeSessionWithOptions indicates an expected call of ResumeSessionWithOptions.
func (mr *MockcopilotClientMockRecorder) ResumeSessionWithOptions(ctx, sessionID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSessionWithOptions", reflect.TypeOf((*MockcopilotClient)(nil).ResumeSessionWithOptions), ctx, sessionID, config)
}

// Start mocks base method.
func (m *MockcopilotClient) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockcopilotClientMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockcopilotClient)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockcopilotClient) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockcopilotClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockcopilotClient)(nil).Stop))
}
